# Author: Grygoriy Kravchenko
# Date: 2013-01-14

"""Produce text output for generating ANSYS APDL scripts
"""

import sys
import time
import numpy as np

def gen_preamble(author = 'GK', gen_time=time.ctime()):
    """Generate preamble with author's name and time
    The <!> sign is necessary to comment out a line"""

    sys.stdout.write('\n! This file was generated by {0}'.
                     format(sys.argv[0]))
    sys.stdout.write('\n! Date: {0}'.format(gen_time))
    sys.stdout.write('\n! Author: {0}\n'.format(author))

def print_mptemp(temp_list, command='MPTEMP', max_entries=6, max_ntemp=100,
                 fmt='{:.2f}'):
    """Print temperatures in accordance to MPTEMP command to stdout
    
    Args:
        temp_list (list): 1D list with temperature values
        command (string): APDL command
        max_entries (int): max number of the property entries on on line
        max_ntemp (int): max number of temperatures
        fmt (str): string formatter. How to pass it XXX

    Command syntax:
        MPTEMP, STLOC, T1, T2, T3, T4, T5, T6
        MPDATA, Lab, MAT, STLOC, C1, C2, C3, C4, C5, C6

    Example:

        MPTEMP,1,0,250,500               ! Define temperature-dependent EX
        MPDATA,EX,1,,14.665E6,13.839e6,12.423e6           
    """
    
    temp_list = temp_list[:max_ntemp] # cut off exceeding temperatures
    
    for val, ix in zip(temp_list, range(len(temp_list))):
        if ix % max_entries == 0:
            sys.stdout.write('\n{0},{1}, {2:.2f}'.format(command, ix+1, val))
        else:
             sys.stdout.write(', {0:.2f}'.format(val))
                
def print_mpdata(data_list, lab, command='MPDATA', max_entries=6, 
                 max_ndata=100, fmt='{:.3E}'):
    """Print linear temperature-dependant material property to stdout
    
    Args:
        data_list (list): 1D data list
        lab (string): valid ANSYS APDL property label
        command (string): APDL command
        max_entries (int): max number of the property entries on on line
        fmt (str): string formatter. How to pass it XXX

    The function prints in ANSYS APDL format convenient for e.g., 
    saving to files
    """
    
    data_list = data_list[:max_ndata] # cut off exceeding data elements
    
    for val, ix in zip(data_list, range(len(data_list))):
        if ix % max_entries == 0:
            sys.stdout.write('\n{0},{1},{2}, {3:.3E}'.
                             format(command, lab, ix+1, val))
        else:
             sys.stdout.write(', {0:.3E}'.format(val))
                
def print_tb(lab, mat, tbopt, temp_list, tbpt_list, max_npts=100,
             max_ntemp=20, temp_fmt='{:.2f}', data_fmt='{:.3E}'):
    """
    Args:
        lab (string): material model label e.g. PLASTIC
        tbopt (string): material model option
        temp_list (list): list of temperatures. Must correspond to first
            dimension of tbpt_list
        tbpt_list (list): ntemp x N x 2 list containing data points. 
            Will be cut-off for ntemp > max_npts
        max_ntemp (int): max number of temperature points
        max_npts (int): max number of data points

    For description of arguments and structure of the printout see description
    of TB and TBPT commands in ANSYS APDL documentaion
    
    Command syntax:
        TB, Lab, MAT, NTEMP, NPTS, TBOPT
    Example:
        TB,PLASTIC,1,2,3,KINH
        TBTEMP,0.0               ! Temperature = 0.0
        TBPT,,0,29.33E3          ! Plastic strain, stress at temperature = 0
    """

    temp_list = np.asarray(temp_list, dtype=float)
    tbpt_list = np.asarray(tbpt_list, dtype=float)
    temp_list = temp_list[:max_ntemp] # cut-off exceeding elements
    tbpt_list = tbpt_list[:max_ntemp, :, :max_npts]
    ntemp = len(temp_list)
    npts = len(tbpt_list)
    
    sys.stdout.write('\nTB,{0},{1},{2},{3},{4}'.
                     format(lab, mat, ntemp, npts, tbopt))

    for temp, tix in zip(temp_list, range(len(temp_list))):
        sys.stdout.write('\nTBTEMP,{0:.2f}'.format(temp))
        
        for x1, x2 in zip(tbpt_list[tix][0], tbpt_list[tix][1]):
            sys.stdout.write('\nTBPT,, {0:10.3E}, {1:12.5E}'.format(x1, x2))

if __name__ == '__main__':

    gen_preamble()
    temp = np.linspace(300, 400, 10)
    ex = temp*1e3
    tb_pt = np.arange(60).reshape(10,2,3)

    print_mptemp(temp)
    print_mpdata(ex, 'EX')
    print_tb('PLASTIC', 1, 'KINH', temp, tb_pt)

    # how to pass fmt to print() ? XXX
    fmt='{:10.3E}'
    print('a = {0:.2f} b = '+fmt.format(100000, 200000))

    # slice and dice
    a = np.arange(36).reshape(3,2,6)
    print a, '\n'*2, a[:1,:,:4], '\n'*2, a[0][:,:4]
